services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_OPTIONS=${NODE_OPTIONS:-"--max_old_space_size=512"}
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge